"use client"
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Header'
import { AuthContextProvider } from './context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(1)
  return (
    <html lang="en">
      <AuthContextProvider>
      <body className={inter.className}>
        <Navbar />
        {children}
        </body>
      </AuthContextProvider>
      
    </html>
  )
}
